services:
  backend:
    container_name: itu_cont_BE
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: itu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: artem
    ports:
      - "5435:5432"
    volumes:
      - .docker/itu-backend/seed-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_container:/var/lib/postgresql/data

  application:
    container_name: itu_cont_FE
    image: node:lts-alpine
    ports:
        - "3000:3000"
    volumes:
        - ./src:/home/node/code
    working_dir: /home/node/code/itu_project
    depends_on:
        - backend
    environment:
        - HOST=0.0.0.0
        - CHOKIDAR_USEPOLLING=true
        - CHOKIDAR_INTERVAL=100
    tty: true
    command: "npm run dev"

volumes:
  postgres_data_container: